name: Pruebas automáticas EFT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar rama main actual
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Mostrar archivos disponibles
        run: |
          pwd
          git log -1 --oneline
          find . -maxdepth 4 -type f | sort

      - name: Asegurar dataset final
        run: |
          mkdir -p data/processed

          if [ ! -f "data/processed/hourlySteps_eft_final.csv" ]; then
            echo "El archivo no apareció en checkout. Descargando desde main..."

            curl -L \
              "https://raw.githubusercontent.com/jjuliiann/proyecto1/main/data/processed/hourlySteps_eft_final.csv" \
              -o "data/processed/hourlySteps_eft_final.csv"
          fi

          test -s "data/processed/hourlySteps_eft_final.csv"
          ls -lh "data/processed/hourlySteps_eft_final.csv"

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Actualizar pip
        run: python -m pip install --upgrade pip

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar pruebas
        run: pytest tests/ -v
